apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
components:
- ../../_profiles/llm-management/non-prod
resources:
- cluster-secrets.yaml
- cluster-config.yaml
