apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
### common repo resources
- kafka-repo.yaml
- knative-eventing-repo.yaml
- uptrace-repo.yaml
- otel-operator-repo.yaml
- otel-collector-deploy-repo.yaml
- milvus-repo.yaml
#- milvus-operator-repo.yaml
