apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  chart:
    spec:
      chart: grafana/grafana
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana
      version: 9.6.7
  interval: 1m0s
  values:
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
        - access: proxy
          isDefault: true
          name: Prometheus K8s
          type: prometheus
          url: http://prometheus-k8s.ntnx-system.svc.cluster.local:9090
        - access: proxy
          name: Prometheus Apps
          type: prometheus
          url: http://thanos-query.monitoring.svc.cluster.local:9090
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      enabled: true
      hosts:
      - grafana.*
      ingressClassName: nginx
      tls:
      - hosts:
        - grafana.*
        secretName: grafana-tld-secret
    persistence:
      enabled: true
