apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
- name: regcred
  type: kubernetes.io/dockerconfigjson
  files:
  - .dockerconfigjson=hub.dockerconfig.json.encrypted

resources:
- milvus.yaml
