apiVersion: v1
kind: Namespace
metadata:
  name: milvus
  labels:
    toolkit.fluxcd.io/tenant: platform-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: milvus
  namespace: flux-system
spec:
  interval: 4h
  url: https://zilliztech.github.io/milvus-helm/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: milvus
  namespace: flux-system
spec:
  targetNamespace: ${namespace_name:=milvus}
  chart:
    spec:
      chart: milvus
      interval: 1h
      sourceRef:
        kind: HelmRepository
        name: milvus
      version: "4.1.9"
  interval: 1h
  values:
    dataCoordinator:
      replicas: 2
      activeStandby:
        enabled: True
    dataNode:
      replicas: 2
    indexCoordinator:
      replicas: 2
    indexNode:
      replicas: 2
    queryCoordinator:
      replicas: 2
      activeStandby:
        enabled: True
    queryNode:
      replicas: 2
    rootCoordinator:
      replicas: 2
      activeStandby:
        enabled: True
