apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
components:
- ../../_profiles/${BOOTSTRAP_cluster_profile}/${BOOTSTRAP_environment}
resources:
- cluster-secrets.sops.yaml
- cluster-configs.yaml
