kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    prism_central_endpoint: ENC[AES256_GCM,data:NgXwf92LhawIJOywvvFxrhjUkcAZU+HL59tOuM71VlgWjbRU7NHc1q/2y4dVMw==,iv:O1W4VjOUZvRn/Xwdq9+3ElQG4/GYyei5Y7oIxyCJTtc=,tag:Iu51cHAEk6Lk5CQ6sXd4GA==,type:str]
    prism_central_user: ENC[AES256_GCM,data:/BcinuU=,iv:/nWHpAx3oYR3IdLNydXgjmEzMi5kvZDAoimbtbXkHOM=,tag:wpgpjubxQFOnYQSJtaTHNQ==,type:str]
    prism_central_password: ENC[AES256_GCM,data:GSORGg/uNBs6VZc=,iv:t+ox+/sl8DB3rjME+jr4BcJYYc/E9TKl8+BTjQpP8Vo=,tag:I3yE0KNxRtVdyAF0QWjJpw==,type:str]
    prism_element_user: ENC[AES256_GCM,data:4veL+hg=,iv:SzC+pF4HBlWlwNuhmIjLj0jg83MBBaKJgtmcIwwZ3ug=,tag:M1Jk3GIKf9XAPfPyxzemwQ==,type:str]
    prism_element_password: ENC[AES256_GCM,data:6JCDNUm8TkogR2c=,iv:BUaQqA1bb6mHck1zS9scflcPk2QrP1QvOkoYQCbrnGA=,tag:z3sXxowQW+0zRfCJ2sIRng==,type:str]
    github_repo_url: ENC[AES256_GCM,data:KUgM6kv2/UfCSYio3R8biI79soTMU92XSyTRMwYHZzyEDlwXFXvPqidHFzToDJPVX4Pkkg==,iv:T2w9cn3KWVbTXbEF5WcaADpsUwzOlcKmwfOozGGceIM=,tag:FUs//MZhXJPraAYXHqzIAA==,type:str]
    github_user: ENC[AES256_GCM,data:+OBK8N3YNX3urjKamt8=,iv:MtZUHpPGX3gxduMe6/BG6NmSOtE2eTgYiQ60zR5JAJ4=,tag:DHcpY6NfQcpAPYXvdmoAbQ==,type:str]
    github_api_token: ENC[AES256_GCM,data:WlRY4FlWP6WkpduxK+tJSYgeGnlQGEfgyqjn/tku/oGTiegBoELz8w==,iv:GnG/Htvp1IRBiUZbTECtSBWjvIx+1UazZJxOc2dSBxI=,tag:zE+Ni25YNdTAhfnEcB9Y6g==,type:str]
    github_app_id: ENC[AES256_GCM,data:d0tlKpq4,iv:vc6m9Hv1MS5O7GCLXS3diDGPr+a9VLBYOAkHVsv96r0=,tag:0V0ox9pOWAc1+Lv6hp/V6w==,type:str]
    github_app_installation_id: ENC[AES256_GCM,data:2eyND5xb2Pg=,iv:BsyXl4Loeqk4bPx8yQAxIp2Ef3xoEd+XbzgcoDAWVQg=,tag:mPAQpHWDj/marhVvf2+RqQ==,type:str]
    objects_access_key: ENC[AES256_GCM,data:EOY+HHrbgwYq5FD0KsKZUPcFoMKKN52kOlPUXaxd8uk=,iv:dTeVE6/8IpHWOPYq1HbvdpBVbpHVqV6jXIiA0OCBvJs=,tag:6h1V3dwBF6pLrEuh1FjbaQ==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:u/7hD9h0MSq9xpxn2soYXS96ujQtt1m37UJmKnWGmWo=,iv:tSYx8ZZbYvdSxwsp447Rkf0cHUTmotn+tYIUzPUXcV4=,tag:H3xn8gUnnAvLxIKbwyuqnw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apnz8w62yg00n3lux9ys8w59e5pxqqrg28dgzy6ajkr82aeq09gslhhm3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyOFl3dWxYMVpoRjBuVnhC
            VTRHVFJvYmxZYXhoNXhhRDVSVWxYMU1Hb1FvClhHYTJmVUNMc3g2TTdsU0MvWDY5
            Y2VFUVhXbWRlTVRWVTVMY0JoTW9kTk0KLS0tIEgzaEdRNVF3U3pmdXNVanp5Ly9k
            OHNhbmxwd3NleTFNSlZOMjVuZ1dQbVEKt4+SRiG1Xo+GnNPF3DwW2sO5Ig1VdCls
            eg9nJcgS7APbmy/dbRbTZ1gZMlEPp5cMXIgJIRJYzGnq7CZ2bZbX3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-07T20:08:25Z"
    mac: ENC[AES256_GCM,data:Zi03db0CCo73tgulD7z87Y9gv24hFs36TXdGhhgNuuzswh432QXg8Y9TzD1p2DoAC5ZQ9Tkl36XxlijDrKg9dg5PQix4KrmQ/73EH5tVbwt1u6vEc6deVd1mV8BR2/8kiRdnCwNJ42E6P0rkofEJ+JJOFdn6SZmqKWXA12UNaN4=,iv:FYAKQqfQi68KwwR4YKKIXKXovJVn3fER4eaTD4AQ9G4=,tag:FmqC2M8UhNf8RODUr+zUHw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
