kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    prism_central_endpoint: ENC[AES256_GCM,data:HE266mSPqoK3icffa0c0u570v3uEqwM1idA5QJf19mM3cs27KauQIrKWvr0Twg==,iv:lCbyc6fp8SE/Q8YbyGjRX2YEmwpa+QVY3k6OAhMXVoc=,tag:pNc8r9aOlPhvgm9NO3JqSw==,type:str]
    prism_central_user: ENC[AES256_GCM,data:bhsDxOU=,iv:dhkMGP04+TmctTlW+sZM3cAWIl9KjiUI+zSXL6pAtfQ=,tag:yT3oRYLf8PuVz3WQy+wZRw==,type:str]
    prism_central_password: ENC[AES256_GCM,data:+VFBwq8PkNRbNoE=,iv:pTffjm1NoJS42TMM58OsAv8/i0iJeHvb5tKa7p1/NeI=,tag:w5/jfva0tXFBQFHywC/dXw==,type:str]
    prism_element_user: ENC[AES256_GCM,data:NuaXwJI=,iv:SrvtHEhNDmqqVQM1y8I4p6eybwvarE4ovzWUqdotzGw=,tag:HWf2xPvp6BE7R4kbNAr4qA==,type:str]
    prism_element_password: ENC[AES256_GCM,data:10Td8CC92dVOqVc=,iv:kZI6lACJ8Z7hK7V4n5KU4/RhWFIQHO64eTq/yMoJB8A=,tag:kO2mSU9RQnwXnKf/vIK+yg==,type:str]
    github_repo_url: ENC[AES256_GCM,data:4G0Gug+qr39u6bKu4mSZLcaNu8dsDXniQZaX/zxGgpBYRYZKFJGi1yy+vdaH1OQmeF0XHg==,iv:lvOEaLCDWISCOxQt5oud7UPdjPTXXEvU79EZPREskOw=,tag:Tt8goIutsd2IDvZv39I/sw==,type:str]
    github_user: ENC[AES256_GCM,data:AWcFcIq1sGMH3qcifTg=,iv:rWC5H+ewwb4neiOqWzOoY3ehwupMOVbroJ1vZsdwcvw=,tag:s2XtClKMvVecwG2Ww9VVsA==,type:str]
    github_api_token: ENC[AES256_GCM,data:4cYCveJ+5Gx78zLkYcebiFFsVlDR7Ehu4vx0Ph9D5NS9bS1s1tTb9g==,iv:/k+1ie88kyTx9OSGBWHPfiyUyCxEu5+ImstKTRzsl5k=,tag:Ht+6pp356qsEC4A6dXUJ6g==,type:str]
    github_app_id: ENC[AES256_GCM,data:okA2HVi8,iv:KAdpLyyNVo70j2BMcDiMzKHat5gZvQkJB9C6/Rk4dKo=,tag:lmCQNiWao+ugmYtb2NmQ2A==,type:str]
    github_app_installation_id: ENC[AES256_GCM,data:ewVG7Wx84EQ=,iv:CVFYazCDqywsLHb+8mTuaTUOyVARLYzsMoRLao51yJU=,tag:DsG/BggNDiQmhV+WZ9vYcg==,type:str]
    objects_access_key: ENC[AES256_GCM,data:mKSTIMZDJDXXFkQbmrySLEoTVIvp+xh8ZgW0/mKNKn4=,iv:pst/KWQcQ/0sucusbVC2mXmSeD0ongZPaj86JaYfnFE=,tag:ibzkF1FLKE/ILHfoYw56SQ==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:AYyDpqp8aj84hgkvZ28HcoDDHwNfRGYgl7a13JQ9048=,iv:gH0pDDNavtm8NzHQBnkJ8Q4yPmrfaZQ+Eij1qIqLuJE=,tag:godFHKhDFnQOvtIyScFefQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apnz8w62yg00n3lux9ys8w59e5pxqqrg28dgzy6ajkr82aeq09gslhhm3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4YlB4UkNkSlJ0QVA1eU1y
            cTlqWmlmcDlVblRqVUxZcnpMVmJhbWdrUGxzCkcxMCtMYWRTUlRsc0xBSmFqQUl6
            SVVHRGVuSFMzeGw5NlN1TDdvQ2J2aW8KLS0tIHdoeEpSNys5c2dMNS9tRWtnUEd0
            N1dONzdzOHpTRFRnb1hsT1NQYWJScXcKEtW6tYraQ1z63jS/Y+sm8JE9KL+52rFe
            LKZBuJfCZjVSw2mHUCTN616DGhMpCGkKKU8/7CgIOeXDGNRYF3NnRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-08T23:58:24Z"
    mac: ENC[AES256_GCM,data:mX8/lN3JsE9DYDH9HH836Yc61pZzS+lFVkwscpOq665FAwOf0Q2vxBGb6zW+S4SUtWSUC9XL1ioRgWF2i/fFhZrd48YjgA9OAXPffdaEo7zgEssd5eojo+tADZcE6RL5qCHv+JuS+oDzYEABhsjtusyvKlFLi3TMAObWbJhcotk=,iv:FONyumi5OKCrHl8RttK4tk+kGwDBRgykTgoWByOoFic=,tag:b9UTI+v+OUQoibaOZMSvtQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
