kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    prism_central_endpoint: ENC[AES256_GCM,data:sUnmB8W12/LZqlDyJES9Ucrae2s5Fzh3ICJ6tRlzpJbQyIsWiwvo32/4tU7amQ==,iv:lpTRG/ZSZ/VXMRcAxGg6Z+PKONmaIsynckXcHonZPW0=,tag:RClRD9C6rkDukAPJk3lWHg==,type:str]
    prism_central_user: ENC[AES256_GCM,data:lnUqZSs=,iv:3bvvIVAMjdBL/VtlttEf1HgHKrnua1Bffj/dsbWxTqw=,tag:1G926HtfPO4irvrsWs4d6g==,type:str]
    prism_central_password: ENC[AES256_GCM,data:wvEmzwrEIoRuUa8=,iv:vJEyHaFgtKYM5GdsogLA/hhX+cxZ6ROOUM1HJLoNJJo=,tag:Zkgggmws2spPbUcI4NmZuQ==,type:str]
    prism_element_user: ENC[AES256_GCM,data:625pjk8=,iv:Rbi/BNWYa5Fz0Gfqh0zSqRI0qWFexnCMEGKsbbDG3Xg=,tag:F94FSuvrs12xJ/Eds6087g==,type:str]
    prism_element_password: ENC[AES256_GCM,data:xrKZXx7dkPg3t8M=,iv:ifpqNgqxuxCMtPPbBtH3lxzLG6nJACwBFwL9xZ4/grM=,tag:lez2Z8qv8xNpT1qKLe4aEQ==,type:str]
    github_repo_url: ENC[AES256_GCM,data:Y2pmtlkosNDr13q4ZOdfcgWLm15aap+MuEhReGs2tV+67Pem0ek6EgHz7/aiUpcYrJzKEg==,iv:3sFmuOksxPSn2LHIE4gbO8yIfi9cvqQHU21IHYZOfdQ=,tag:LIRECTqCnRYCO2f/Y4wSdg==,type:str]
    github_user: ENC[AES256_GCM,data:roqpZmS7oJra0MRY2Cs=,iv:yCWPCAoOzHSOp15h8EvMqjdNktSaEJpuXKvZNjwZAWo=,tag:lqt2yGZW6K/BI+KqaY4kzw==,type:str]
    github_api_token: ENC[AES256_GCM,data:tgVMSwWxtM0yApzlw+Kc9NZagZhZYCuvhD9uiah+hdz3UM2EnWHwYw==,iv:VgIRfy71PuErtuZQmfk5NwtL/YEOI9bDjOtsSVmC7RQ=,tag:2OitkusLGumG/F4FdNHsnA==,type:str]
    github_app_id: ENC[AES256_GCM,data:SwWL+hEs,iv:9g9DVwOd92SSkqNslNaUJ9YFn7yBQSfx7+lZ+lay3F0=,tag:Xumh2vcgMeItXjf8z9aN6A==,type:str]
    github_app_installation_id: ENC[AES256_GCM,data:yrWl6qAqTP8=,iv:9eR8HsZV/BRMy3KjVYiuOHF/X7BtJPFxmgEBX9a1czg=,tag:YFxn0ZgFaJ7TrA28NukWDQ==,type:str]
    objects_access_key: ENC[AES256_GCM,data:jEx1i3d3QH43z1bl8CovtQpuOOhitabRxauQKHZZYIY=,iv:+ilYmaT4sOD4/1maP94rq4ZF2eqPowhxHwA5iS1rXRM=,tag:tF0beT9UgAl6LxmAK4Nt4Q==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:7Gpj2Jmy+ewTrIneMFhmOsA50zYyS2G8Ae9HqxnArs8=,iv:VgThEA+ah2akrU+X6QGvL/15DMKLV0m7HaPL+VNKAq4=,tag:GCdiUylqu8wJJ3pGh5Q60Q==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:B5sag/JpkMM=,iv:GZzqAn23A0hylNrq7av2cOJnOyuFBa7Hu3AjA4YtGcU=,tag:VYT2x3RnnTMJ5ROzFia/Mg==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:rnWoXlMYaBg+wdBf2TfleydijyvMN1+4XVgP6Ac9jO7QxUMM,iv:p9YPEkAi4tRzKte+mTNIY1Ku1dKAbDXHOfQsrbFPqcM=,tag:ECGPl1Dj2biHkqwcu6mSXg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apnz8w62yg00n3lux9ys8w59e5pxqqrg28dgzy6ajkr82aeq09gslhhm3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPVUw5aFZ1ZTFLZThpeTMr
            ZEl1bVRKK3habi9jcTU5bWR3S2o1VDlZQ2c4CjB1ZTNldGJPQlMwLzlwdG9Fc01V
            dkJRWXhDUWViRDlEVUd6M2V4VVhJcTQKLS0tIGdrK3NNMVZHa1JVcXhOTEhJN3c0
            Y0xuLzZJdzg4M0ppR3dKYmhtWlBjK0EKeLIruWQHwW0bbVfN44oQRyrBnlqqqMRL
            nfj57UdVgBc47559jvUESJdRNts4KE+0kQyb1sbySUfr0j/14Q+U/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-09T15:06:49Z"
    mac: ENC[AES256_GCM,data:thoxESbvV4Mz6llkYcxK0SLqNE0bsdrOKSkeK4rS01fKWbd5+oPwTl60HsAuJRWj+mcxtxvDDk5vgFeVJiaOqEEONE3BQl9M5yo17GQCWPW5qXVXGe3G73I9sO2PkqK+qhxIotciN5tHOZXHBoZyYxBSEWbKjsKb1m05cAebe0w=,iv:P8fTBYXNtW+/ARYb7sT0R2L1NF+CzNtf8YNnTRwO9mo=,tag:XryAESa3eLPlRpZ/OymjVQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
