apiVersion: v1
kind: Namespace
metadata:
  name: milvus-operator
  labels:
    toolkit.fluxcd.io/tenant: platform-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: milvus-operator
  namespace: flux-system
spec:
  interval: 4h
  url: https://zilliztech.github.io/milvus-operator/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: milvus-operator
  namespace: flux-system
spec:
  targetNamespace: ${namespace_name:=milvus-operator}
  chart:
    spec:
      chart: milvus-operator
      interval: 1h
      sourceRef:
        kind: HelmRepository
        name: milvus-operator
      version: "4.1.9"
  interval: 1h

