version: '3'

env:
  K8S_CLUSTER_NAME:
    sh: kubectl config view --minify -o jsonpath='{.contexts[0].context.cluster}'

dotenv: ['configs/_common/.env']

includes:
  helpers: ./.taskfiles/helpers.yaml
  bootstrap: ./.taskfiles/bootstrap.yaml
  init: ./.taskfiles/init.yaml
  kubectl: ./.taskfiles/kubectl.yaml
  nke: ./.taskfiles/nke.yaml
  flux: ./.taskfiles/flux.yaml
  tofu: ./.taskfiles/tofu.yaml
  sops: ./.taskfiles/sops.yaml
  test: ./test

tasks:

  default:
    silent: true
    cmds:
    - task -l

  print-vars:
    cmds:
    - 'echo CURRENT_K8S_CLUSTER: {{.K8S_CLUSTER_NAME}}'

