version: '3'

dotenv: ['.config.env']

includes:
  helpers: ./.taskfiles/helpers.yaml
  bootstrap: ./.taskfiles/bootstrap.yaml
  init: ./.taskfiles/init.yaml
  kubectl: ./.taskfiles/kubectl.yaml
  nke: ./.taskfiles/nke.yaml
  ocp: ./.taskfiles/ocp.yaml
  rke2: ./.taskfiles/rke2.yaml
  eksa: ./.taskfiles/eksa.yaml
  fluxcd: ./.taskfiles/fluxcd.yaml
  tofu: ./.taskfiles/tofu.yaml
  sops: ./.taskfiles/sops.yaml
  test: ./test

tasks:

  default:
    silent: true
    cmds:
    - task -l

  configs:
    cmds:
    - echo {{.GIT_COMMIT}}
