apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
commonLabels:
  nai-llm/profile-name: ${profile_name}
  nai-llm/environment-type: ${environment_type}
components:
  - ../../_profiles/${profile_name}/${environment_type}
resources:
  - cluster-secrets.sops.yaml
  - cluster-configs.yaml
