apiVersion: v1
kind: Namespace
metadata:
  name: opentelemetry-demo
  labels:
    toolkit.fluxcd.io/tenant: platform-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: opentelemetry
  namespace: flux-system
spec:
  interval: 4h
  url: https://open-telemetry.github.io/opentelemetry-helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opentelemetry-demo
  namespace: flux-system
spec:
  targetNamespace: ${namespace_name:=opentelemetry-demo}
  chart:
    spec:
      chart: opentelemetry-demo
      interval: 1h
      sourceRef:
        kind: HelmRepository
        name: opentelemetry
      version: "0.28.1"
  interval: 1h
  values: {}
