apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  ##serviceAccountName: kustomize-controller
  path: ./platform/cert-manager/_operators
  prune: true
  wait: true
  timeout: 5m
  postBuild:
    substitute:
      namespace_name: cert-manager
    substituteFrom:
    - kind: ConfigMap
      name: cluster-vars
      # Use this ConfigMap if it exists, but proceed if it doesn't.
      optional: true
      # - kind: Secret
      #   name: cluster-secrets
      #   # Fail if this Secret does not exist.
      #   optional: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-resource-configs
  namespace: flux-system
spec:
  dependsOn:
  - name: cert-manager
  interval: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
  # Decryption configuration starts here
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  ##serviceAccountName: kustomize-controller
  path: ./platform/cert-manager/_resource-configs
  prune: true
  wait: true
  timeout: 5m
  postBuild:
    substitute:
      namespace_name: cert-manager
    substituteFrom:
    - kind: ConfigMap
      name: cluster-vars
      # Use this ConfigMap if it exists, but proceed if it doesn't.
      optional: true
    # - kind: Secret
    #   name: cluster-secrets
    #   # Fail if this Secret does not exist.
    #   optional: true
