apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-vip
  namespace: flux-system
spec:
  interval: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
  # Decryption configuration starts here
  # decryption:
  #   provider: sops
  #   secretRef:
  #     name: sops-age
  #serviceAccountName: kustomize-controller
  path: ./platform/kube-vip/_operators
  prune: true
  wait: true
  timeout: 5m
  postBuild:
    # substitute:
    #   namespace_name: kube-system
    substituteFrom:
    - kind: ConfigMap
      name: cluster-configs
      # Use this ConfigMap if it exists, but proceed if it doesn't.
      optional: true
      # - kind: Secret
      #   name: cluster-secrets
      #   # Fail if this Secret does not exist.
      #   optional: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-vip-resource-configs
  namespace: flux-system
spec:
  dependsOn:
  - name: kube-vip
  interval: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
  # Decryption configuration starts here
  # decryption:
  #   provider: sops
  #   secretRef:
  #     name: sops-age
  ##serviceAccountName: kustomize-controller
  path: ./platform/kube-vip/_resource-configs
  prune: true
  wait: true
  timeout: 5m
  postBuild:
    #substitute:
    #  namespace_name: kube-system
    substituteFrom:
    - kind: ConfigMap
      name: cluster-configs
      # Use this ConfigMap if it exists, but proceed if it doesn't.
      optional: true
    # - kind: Secret
    #   name: cluster-secrets
    #   # Fail if this Secret does not exist.
    #   optional: true
