apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kafka
  namespace: flux-system
spec:
  values:
    externalAccess:
      enabled: true
      service:
        broker:
          type: LoadBalancer
          ports:
            external: 9094
        controller:
          type: LoadBalancer
          containerPorts:
            external: 9094
      autoDiscovery:
        enabled: true
