apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
- name: regcred
  files:
  - .dockerconfigjson=.dockerconfig.json
  type: kubernetes.io/dockerconfigjson

resources:
- milvus-standalone.yaml
