apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: milvus
  labels:
    app: milvus
spec:
  config: {}
  components:
    # imagePullSecrets:
    # - name: regcred
    standalone:
      replicas: 1
      serviceType: ClusterIP
  dependencies:
    etcd:
      inCluster:
        values:
          replicaCount: 1
        deletionPolicy: Delete
        pvcDeletion: true
    storage:
      inCluster:
        values:
          mode: standalone
          resources:
            requests:
              memory: 100Mi
          persistence:
            size: 20Gi
        deletionPolicy: Delete
        pvcDeletion: true

