kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    prism_central_endpoint: ENC[AES256_GCM,data:GN0DtAgv2R5fmIv64CfxAgrq0nfYHA1irfTKmPzTlpYR+VFfBMcksrmdVP/DPw==,iv:5v2+ao+JlEzRScUsuLWBo9cJ18yxu3+TaTGWXYSsHyg=,tag:csu6Nks8D6mKZpJvJG+kBw==,type:str]
    prism_central_user: ENC[AES256_GCM,data:dIGD9UU=,iv:LlZwr67iQ+WsrDETqRy7Lev8lMKNiLyJhEY6skkxjhc=,tag:8P+jBz6fEvyP72lT0Mty0g==,type:str]
    prism_central_password: ENC[AES256_GCM,data:6ZQ+8Bqc6zCDTDM=,iv:OQ7oCejR6wqYJjlHporHh6TVAEESvahqa015qkPeCN0=,tag:Bv0memP2VzMVWsGai8S6/Q==,type:str]
    prism_element_user: ENC[AES256_GCM,data:jrcrlWc=,iv:RhjDqdznkC4CeHVfLaLfpMNnupuAv296Y+78UXHpp2Y=,tag:eSsxCrfw8TQiLNsv2//pbQ==,type:str]
    prism_element_password: ENC[AES256_GCM,data:MwUI0PFopNztHPo=,iv:lpVbTpHU+VT3PZyGUHioI+E+xjSv6lmjUcL6MrQ7cmQ=,tag:EmmKyUj9dqSs8P6Fbp1INA==,type:str]
    github_repo_url: ENC[AES256_GCM,data:+h5Cc9Ictv8RoFkWn4KPhExkr2HceTrq5j0wzzG2YvyudGih28sfhUc1ZCLrSKtNmhT1WA==,iv:I78HtRFTC2KBYG9QaCrlEiZQIpMcO+4IQhNrd50yoOo=,tag:lLLvybBSrzZaOwT49T/Zig==,type:str]
    github_user: ENC[AES256_GCM,data:xxeWRWwQdAoFusFjB6U=,iv:GmI5L8/PtxhLTkPU68CzBUO9bZk5XlKN8dWwHpKul1Q=,tag:/P1Rc2V7u1YN+N0tXgeTmQ==,type:str]
    github_api_token: ENC[AES256_GCM,data:Hb4xBkG1uoUjU+bqg5/pxTe6cfIA3NHCPNI9MQvcD3598J5wbjEfIA==,iv:iUOHtLWnhCABd1RuwVahOBoHZocvoPQfe4+8ac9LNiM=,tag:AZ2oqyiESAKvuVkyuxNLvQ==,type:str]
    github_app_id: ENC[AES256_GCM,data:191uY5oN,iv:oBPndZYniPdMrtgiJlNQFvgl3BP2AcUEV+bT8CsztLs=,tag:WnbwnH9Pt6qyjfU6d2loaA==,type:str]
    github_app_installation_id: ENC[AES256_GCM,data:RCArrCkf3PQ=,iv:Kd1PLzIPYQcq7hyIRVlk74S5R3d/9gsVaI/L33PFxLI=,tag:sdBVJOyZ9egufCq/kz+KuQ==,type:str]
    objects_access_key: ENC[AES256_GCM,data:MsGDbLLYjafEq6Ihr+IK6u3J5dG2ns1e90vuRLVQW/4=,iv:MtHeVmVG5mERX6p74l7OZZWDscwXS6FLlJ6Kfbxaqig=,tag:pqxJmr6o5YzIN/SSRahRDQ==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:V+4ewOdtI3K8h6cxB+vPP9eEl6DT4j8HWKzIxGnYtd4=,iv:9ngOpclGTR0JaUdD972oArt7NNYw6iOS0WHwgprZczw=,tag:NiaEpuwM3+Pvdx7cE0QePw==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:qZScD0bpDSQ=,iv:+wbYOT7kht0KF2Y1N8Gd+Z+LyP1wODKIZxCwE3Rx4MI=,tag:qN4UKi2UiLdKKfjbSQT4Gw==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:THdZmNXF2bh3/DNJRFfilOi5tdu6u6OQ8ZKM4pniooHp4v5j,iv:Cdq9HOudE6NTKcH1Bufs8DfBKnWst0Aqaoid3qcIUYc=,tag:OEztRJQtnudvr1Rmz1NFxg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apnz8w62yg00n3lux9ys8w59e5pxqqrg28dgzy6ajkr82aeq09gslhhm3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQNFlxWWFsNk43S2U5YVJ3
            Nm1sdDBaTVJHTHpHaHBXNmRKa2VWR0JzaVVnClI5Y3dDK29QQ1lxUk1BTklMVXIw
            eXN5MXU3OVFNc2hiNzFBUDR2NGpVa3MKLS0tIEUyWSs4MktNQkFmaGdPNnhkam9R
            ZXZaTG1uU0Ird3grRFo3eEl5Y3RQd1UKDdeLXWF6WByX18MxfVMNqofy1gGAXHJC
            s3v9difL0Y2ifsWIJV5WPlZdfCokRV7/DH11VnXCGCetlv5Gx7EhEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-09T21:43:00Z"
    mac: ENC[AES256_GCM,data:6ljgRtlE17BnTpU8NwJ8UPNlx1bOgzxMiw+G+1ICxmwfzFPzPCQYYG6U3V8/v0eZ392ZlZBJRuSm3CQSVuKGIzAIATNeWu1yDov8jayudmYrU6HFIIzjWvXc7ssnTiGmqftPo3bCIjsKn0lkNL9EaLsHYLthNUP04bSHbgk+mE0=,iv:NcQVmN7TXel8PHZz7/zwIajoRIWedW6diUJF/HCn+ZU=,tag:RFvXfxPlWXYf2sXhZTyztQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
