kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    prism_central_endpoint: ENC[AES256_GCM,data:WlWBLlPr0G4QEO/HtNBIt5KCyppvupKAqyVS6JzmsMf7x98FWJcErxeuwTVW6Q==,iv:IBRg+8lxU7Ba/+qMGcCNCYujCH+upsfAJ7rJg5LOnEk=,tag:YVLrewrGhUuZzIO913j4Dw==,type:str]
    prism_central_user: ENC[AES256_GCM,data:xoAsuVM=,iv:M2hrb1ZmcYhoa1ZdI8aWhFzFkbtP2J7fTym54ez/kcw=,tag:JWtL8XopmnnHFJHBxbYHbw==,type:str]
    prism_central_password: ENC[AES256_GCM,data:tY/iEmV4xrkwMTo=,iv:yrCmpMyCicuPm3S2xQWLiqqD/rc4ZX1z+Da+YNxEB+Y=,tag:SwmOUciY1zguM/GdVUaTSQ==,type:str]
    prism_element_user: ENC[AES256_GCM,data:tsHro/o=,iv:FUHwvBhOCVdVRJbZPFM/3v1KeDQO2XE15RF1lB7PlSA=,tag:W3ZhH3ZJlPodUiTPvlTwVw==,type:str]
    prism_element_password: ENC[AES256_GCM,data:rB4QaooAru4NZPY=,iv:AzXG9423LzNPgjHS3PixSzAqcYE7xSFbMhtRGJiwc40=,tag:td5c0i1pMun/s0tG/9fWWA==,type:str]
    github_repo_url: ENC[AES256_GCM,data:vS6ezPeeu8oWwCzWRYR5fLyoNpUgfQgEN72ivP3O0sS4l999eXSZlDA1EbsdT/0+tixj5w==,iv:uA/2hzPzyqli1+gj1rWGKRpk1ByJCU3uEPvCbY1EEEg=,tag:Bqa756rpihEstzBQBCQtPg==,type:str]
    github_user: ENC[AES256_GCM,data:ijwmGPlwOj5dR+P1VpI=,iv:MU3JM2Jc8O1PxMejmHqWdQgPYDm91Y5rrzZJs1Bx0fw=,tag:oO2iW3NDQrCfKGNARZwr5A==,type:str]
    github_api_token: ENC[AES256_GCM,data:dftFgxsPhvex7tw6+0tZuU6Tfi7tGwD22uANIPB39m8OI9Z2FQYmlQ==,iv:RYWV9+elJdaN3w9ikOtTBjlNDrZ3HBoW8jxaD942HV0=,tag:NMMu9cCMSuOUWhKO3R1HmQ==,type:str]
    github_app_id: ENC[AES256_GCM,data:XlgJGl2p,iv:exq9G4b6rE1w2/gLmnGGBfhzH6FazzHhnm7hxHahZWQ=,tag:waI6bsDDUk5tCQE/xEckMg==,type:str]
    github_app_installation_id: ENC[AES256_GCM,data:QwKKDE8c7FM=,iv:PwGHiXciJeqtp0YDxeOU3+j+8mjm75q8+M07SgPicnk=,tag:+HpR/Iefyi1gru2QqmDTsg==,type:str]
    objects_access_key: ENC[AES256_GCM,data:UbOt+LlLeLqsaeyd5iciNcyX2JMot46gixoCzMh+DXs=,iv:LlrmGqQL5voNlpwWyCiSatWN1bfwHRvfJeQq6VbwwCk=,tag:bIZ5cWaTJ47hNLxSoaIO5Q==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:E++yDnLt2ldJ+2WomJAFxw7kwPw6ntd9bZDL6rOg+JM=,iv:GV0xE2GwETUr+/qsmxxUHT2NnE6jKVwfj+7VcYywv1k=,tag:vsGW++gpnblAz6buQFcojw==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:4mPUtH2M1rE=,iv:vBwpVUbBmO3QSVkPIdB+SQ8/h2UonZq1jPkY98N5+9w=,tag:8+I1GuZx1+MJM83GDLE5dQ==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:09WD9wODOffZDYkZCuA1NLhXlAmLj4dX4gw8izEcoHr405M8,iv:Fka9blSezXyJaaonP314mTahHMzrRJba0WuVJbCDdCk=,tag:/ATCWUUtxOPMuXFWpbXPjw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apnz8w62yg00n3lux9ys8w59e5pxqqrg28dgzy6ajkr82aeq09gslhhm3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKelRFVmlwa0t6UGJYUnhp
            aVhrWjlaZUMyRnNjbVdzenVxbzA0ZWdvRzFRCjBLeFBkdTlQdmllaXdmQmdGaEJB
            OS9MM3BLK29mSUhhZjdIdTNsTkFZakEKLS0tIFZpZkp1WkVHbVR4L09qU21wb0w5
            Y3RJVElIT2I2eGM4NUV3ZnJuditSRHcKu3wQ+tbVYyI7BsWtyqDu3E5Amsg+b07k
            O3KG0Wfhb6yE/QvnS8tdfWE+5vabBVP2/Vaznl3iV+DIwCKS2AJF6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-09T15:05:59Z"
    mac: ENC[AES256_GCM,data:dPxJgmf822HB2Z/0ZjXcfWCdsaYJmyb803GduYmdU5T9mWXB4/D1QRjZuFjUtQVIQ5T1ikkR/+RJNAJEdltqRUTQIWvABKAqKc3HdnyDnNa2QHMhaLFNr03QQLU6JcITz0GSX5rt5jm9EZc9ICgyfiE5gszDQaoyUl/9uV3NZh8=,iv:/QCsvMGdoKULe/Wo1M/piljneSMicxx7W3aCYG3cN8c=,tag:MbkXVCSAugY5uE/GgulAVQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
