apiVersion: v1
kind: Namespace
metadata:
  name: sealed-secrets
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: sealed-secrets-repository
  namespace: flux-system
spec:
  interval: 5m
  url: https://bitnami-labs.github.io/sealed-secrets
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  releaseName: sealed-secrets
  targetNamespace: sealed-secrets
  interval: 5m
  install:
    createNamespace: true
  chart:
    spec:
      chart: sealed-secrets
      version: '2.7.1'
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets-repository
        namespace: flux-system
      interval: 1m
