kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    prism_central_endpoint: ENC[AES256_GCM,data:Z97itVFMnPVuR0bG1jBwi4bRFGHxJ4fQ,iv:XECYX3WCJHGJrNOPYUCCD19l7M6vH5HJHuBbPrlaqWo=,tag:VZZPHFek2oJFtJKnf9/tzw==,type:str]
    prism_central_user: ENC[AES256_GCM,data:084CbYs=,iv:NXOp0d3kt8dBj1IJmeehqPd8lxaBayg1MDPlmUBe4aE=,tag:VvWF4ASkWc5RG7mVAya0KQ==,type:str]
    prism_central_password: ENC[AES256_GCM,data:82kemY+lJwJ78tw=,iv:vZOUr6VjelzZHDnSLboKw4WqazK3R/f3Noaryhjgs8A=,tag:Qhlz3BeYicC3fEi2/JLrlQ==,type:str]
    prism_element_user: ENC[AES256_GCM,data:uTokKiw=,iv:eMFdI8tJZvAudDbjMvYwcIE+rTY9Oao4abto7VIcRzc=,tag:NBjaUkYROPuML1ZRsVeW2Q==,type:str]
    prism_element_password: ENC[AES256_GCM,data:V1L9+cbjyyarWHs=,iv:KHizNbqUEmkm05NF1eU4ZKcGbGiWxatmbQwB3cGIQGU=,tag:R+uYW8rJPts33zA5SPK1sA==,type:str]
    github_repo_url: ENC[AES256_GCM,data:j4ITEXWLDWZY+ufm5A37lYGNOdT103sCaRNjiA2b3+UiTizzQw8MOZdIci5p9TDyKCBgWA==,iv:IAZXseKDRvEFh7NW9tCVq+S5VPcqPzCx7dCl6oofP2M=,tag:EovcMMv6MQMjCJ7FBRK3GA==,type:str]
    github_user: ENC[AES256_GCM,data:tFdAzxQs7NihDeG2obg=,iv:f7LiocwIJinfySlYR12y21PoysXNMz0kmlFEJcIARVk=,tag:exj5rrgDVF1+fhMf/jW7KA==,type:str]
    github_api_token: ENC[AES256_GCM,data:D3iBF5QDrPzSe8szEYZopkuyLk2LpjXRsnleywgoR82p7oST1GeACg==,iv:s08ZupVK6m6mnG/z2KvbYe6jnUJQzraDCJDJqBOoNag=,tag:viPhLJ/DtI+y66gP0AyATw==,type:str]
    github_app_id: ENC[AES256_GCM,data:M83Aq+Yq,iv:QxEo1rHtdzh0+CosYx6ox/oDXrHZApvpgAUNwJimYso=,tag:eYkqvDO4Yk3A4x+kKwKjJQ==,type:str]
    github_app_installation_id: ENC[AES256_GCM,data:D7vOnqokjg4=,iv:HInEDSsrRzjCOzsFzyqPrlCMAZJvyx++01MyIMMwzh8=,tag:qjnH39RHYyqLpxTnfwVeNQ==,type:str]
    objects_access_key: ENC[AES256_GCM,data:KCOCduvjp6GXogEasQZKfbbVdaOVjS9LeEBMXew8ElA=,iv:ogUMcwpiAyiWxpgi1vpp7OOvfP8pqd+xymFPskP16h4=,tag:WNwklFBu28NOSsS/AfCMWw==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:mEDl3Bej9XY0OItlORxOKwLYlItJW8cIdYQomQ6nEfw=,iv:z9thxx1wIJMnZuZ9Z1uEpd/aJhNmK6kTHWGpn2rNNTo=,tag:cayOOSRf5BKfnnNlrfJX7g==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:pputjr2jILU=,iv:ch94nyNriw4gQnR2V2KpOyNxgp+zNsqGZLq4rb+kVCc=,tag:hv2ja8sx1+vmzHD7UfbKHw==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:kIhEofhweqIa4uxpAtMASc4vp39dpyyMlW9YS1d3YitDaW7a,iv:2JIvSyBrJGz8U9w9VSjkClMF1qTTT0na4QGP9z4N+W8=,tag:i1BnUM+DbcRL1uN3JzZrOQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apnz8w62yg00n3lux9ys8w59e5pxqqrg28dgzy6ajkr82aeq09gslhhm3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqUzVVaElmNmpKNENWNkt2
            YURLQVBiZCt2czM3QnRXdnRQMFhBaFlCNFRvClJhTU9NRkVhZ2V4dGczK0hsUElN
            aHVIZ3VwVFNjWFFOc0xUK2FkNWVicTAKLS0tIGVObHRIbWFnckJYRm5zQ2ZvLzFJ
            YWxMekF5V0dUdU5DY0lFZ2lWSTVPdGsK3k7dzVtfswDG0csREGjRn3ETKGJGmks8
            s1/v7LuFWa9AAEgBgWnFvOPJsGer2VsP5WTr5I1NC/oBfw0GXXL0JA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-19T21:45:12Z"
    mac: ENC[AES256_GCM,data:lTOj7DPVUoUR8Q70CwoDczyXLiIzl3zONYhF19gHRr0g2eOIqJ1nTxWk9LjUTRFI+nHLCr15e1CUfZuxFoX9mILxbYJKYdS9VlOgR/e7bS6Dpd8kHUaxOd4aJoQhzGN4cjLokAeQG9TbRwwygGyTeumuexzYuuA/HVROiDLeiAk=,iv:OH4YDKpeY1ESKoPygp2KG6hw/hAq3l43xhPfNNXh6LI=,tag:OwCfLaAyJQYCvfGnAVdOIg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
