kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    prism_central_endpoint: ENC[AES256_GCM,data:V5na3yM7bmZVthUXEeTULYtJ77xv,iv:8GjSnGWeaFdTxcua325jFzCnC5ZSY0AxgWtesYWgpxQ=,tag:P5Gokf83ZwZVzSIsh/klbQ==,type:str]
    prism_central_user: ENC[AES256_GCM,data:9X9Wa74=,iv:sLsJRl6FpW4J87dIcmVUNRhBMtIrrCKuwDKRou07B5Q=,tag:ZOjkvkFCv9uOMWohI0/ZDA==,type:str]
    prism_central_password: ENC[AES256_GCM,data:0MogJedvcUhKCio=,iv:ENmKxp62lpNDhJuo0tWEc9bgFBz3371faN5V/ZzjsHE=,tag:UnmBVMk6+ZtWld7R8WyD+Q==,type:str]
    prism_element_user: ENC[AES256_GCM,data:oChO2dE=,iv:4TvnSwHiIgJhhMHia09GH+zpkxE2fGTARnQpLGwdCTo=,tag:zGeOFqVnbCbLzCeNuHdbYQ==,type:str]
    prism_element_password: ENC[AES256_GCM,data:4ZxZz4hpQqxum5g=,iv:pAQKIVRGOsGx0PLSBnQtRa5FJR0tkBrHFPl52t/I2GQ=,tag:7w7pOWt6lZIbhenqjPMMDw==,type:str]
    objects_access_key: ENC[AES256_GCM,data:6rmY274nIuWi+4607ZE3sInzhX5v3R5xbIdt512Alto=,iv:A9dBuHi+01fQPZy8dLjc5FT2yuW1y0dNCAi03qBc6dw=,tag:FrqIA0oxHtmaXxjM1LaDcA==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:CaA9yP+/ftwL7CZDRwSK5LzSKdlW5D1PqcYfDsPIeg0=,iv:AZFFLkDngZ+8C2exLZ02stCMPNZPxYYoFfc3cG/1XBc=,tag:RM6kqucgWNKtoOtbHFHHeQ==,type:str]
    github_repo_url: ENC[AES256_GCM,data:gojJcuSA5By0bFY3w7BW1MAYMPvQoXtT4qYkqfAdVeqcQDMrHrH3P6RDsWZgHQJE4ppRbQ==,iv:uecs4FYY0dv7lAk3IEgGZymRjBOBBYTQj8A3ya/C+ak=,tag:Vl3fMq0mkCLJTme51mx8fw==,type:str]
    github_user: ENC[AES256_GCM,data:dJzaZRrL2ugwPdrmzXw=,iv:aKAn7vQbtSGw9UgI+6fw21JK8nZxlHINKgdYo/khdBg=,tag:PDiqqnRrqVvVZ8rGby6RjQ==,type:str]
    github_api_token: ENC[AES256_GCM,data:TrUQWL1vArqrlOzFvmO1RiQ0sU3I/XXTThlU6GHfZDxPWuREe4M/0Q==,iv:v4DqseYCNOdo49jSnLjla8skHthPgAPi2nhdeTTacoQ=,tag:B1aP/UuzmNLIeuH4rRzBIQ==,type:str]
    github_app_id: ENC[AES256_GCM,data:imVSudiV,iv:br6fS8zXq7t81xrot+uPkJqR2V74G//2w3/JuV59C9o=,tag:5pOcYmptZqzgrZlBk6V+Vw==,type:int]
    github_app_installation_id: ENC[AES256_GCM,data:bkil4HodS7w=,iv:YW3vr9GtyJqjCr/IfFyfU+l2qhdhIvSN/GZY1XLmhc4=,tag:I/BjMEAsj63x+4K5UdNihQ==,type:int]
    docker_hub_user: ENC[AES256_GCM,data:pA2pFSOEo2Q=,iv:VMUDQgmji9WPqZzbhiAJ61QCt2gmRpcxznwCLoYmhgI=,tag:wZem8fsd8OBqKxqzW9BnLQ==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:0rY6GzuSQP88nFfHLe5qHwxPFKmT8qPXQJ4SlZea0K+/s59U,iv:owAL56PKwMbHQgXKhLzoB/1mIJUwXS7e6W1yM4sfCGI=,tag:5kIwgiEv781fquqZaux3XQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apnz8w62yg00n3lux9ys8w59e5pxqqrg28dgzy6ajkr82aeq09gslhhm3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZG1UUnZWdFdIRXF2Q1E4
            TmlMVVBYNit1U0c2azRkcTFhYVo3eFd4Q3dnCkFxWU5ic2pnRXRRMHppL1Vhbm1n
            T3BuYjh1R3A5czN6MzZaOFBud2hhNHcKLS0tIEw2MFdYM0hWcmx0dnlhVDZjSWow
            MXFQelY5S3FOUDZ0aG10ZG9kQ1hQQzAK0Hbgum1CXomgb+dfsIPV2qz10sIKjzRv
            LnVHe1Bj3BvCN4rsTYY68p7v4VQxF0d2o9frXhJMxdcWacC40y7NXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-22T02:45:36Z"
    mac: ENC[AES256_GCM,data:qgu/ySXckyYoJgaUuoEQCr7A/wjr3iHLj/bgDH/S0O9pfZEfv76nTcn5oqiBQjjBfDVEKFN1xmzb13Qe4MGKzvkrst/O5fX4d9bgO9peUgjEKeJWHkzcbBIEdx9TSkD35co/tvy/QRhLbwgFncAm9brbugSmTFtAvgcgni/cvtw=,iv:sDhvLVRu9ti+gcR0dCwAGWhGj3IETezmpmVjH5AyxS8=,tag:bpGVeAgsiqZVyTVcgKdOpA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
