kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    prism_central_endpoint: ENC[AES256_GCM,data:twuLQ0ocjAuX/yfbiegjTRQRx58o,iv:k5XawJTKL7DfcZrTtniCjn6dJTIzoZYj4vvgTBLcRXI=,tag:4jU8A0pBnd2wMZIFyFONFg==,type:str]
    prism_central_user: ENC[AES256_GCM,data:j1BEYmY=,iv:xRjuBfDTby9YtLBRDyBIIVvSNX00qUafQubL5g9HED0=,tag:523SXMZydXjbNcpWtQmSzA==,type:str]
    prism_central_password: ENC[AES256_GCM,data:x1JqzKBOx08Ijlw=,iv:msFc/nESbyi98toM+xbTjcWxkn+tVb37dQhiTbuk600=,tag:bGwOtzeNaG80XHTg29LlpA==,type:str]
    prism_element_user: ENC[AES256_GCM,data:oCktZkA=,iv:J1vkjeCN3u93Hd/lp7sK4Fx6yAXmp3tR6F9rMw/G46M=,tag:dY5cCJh/n/eEyZ+Dk+im1w==,type:str]
    prism_element_password: ENC[AES256_GCM,data:4p5m34M3UHiqSLY=,iv:Y/Fh7Qj9iaKiiCPkLcHv6BvlKNSFACkn7UbSrymH16E=,tag:eBYebpcRaLluePYEi3YTrQ==,type:str]
    objects_access_key: ENC[AES256_GCM,data:ZGMyxDXCLTFyj3s8mBKNs3/0iFqJVEu0UKe+GCaaNJQ=,iv:LLcsfJZTwcQjsFxpKwViu+GPhZF1MG42YGMhQ1/NYGY=,tag:owjBO0wB4h70+yt2sSa+mA==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:2OcfTjMUE7HQ43j+eK2bKcnlencSPpCRd4OHyUdMAKY=,iv:ElO609BXW/uoPxyWQNPVyW6xv2iL5exOYLbz/KUQA8M=,tag:zTZdDc2RbG8iEypJMjnJTg==,type:str]
    github_repo_url: ENC[AES256_GCM,data:AidXbd9G++HxjzWmIwEMrpvP0H9Pt4r4ajJIY5A7bfhIyP9f9e6jEph2LNtJcZJr0j/kbg==,iv:pId6JL/UsV4hSfMeAVuwFsrNWKnqu7640GxQ7VnZwxA=,tag:GIhPfzXwWeZ7KuFfp0BGYA==,type:str]
    github_user: ENC[AES256_GCM,data:1dqLeTKw7bLRLHYyhVA=,iv:X3BEp3uBQJQYXZsy5GwaGoKi2xlsd8eVbKMHMRiG2Ec=,tag:/oiN+3WOgsSWW416CIesKg==,type:str]
    github_api_token: ENC[AES256_GCM,data:GEivQfuRqXksI4qkJ/6Fz+tZT62SfzWpCCQxlg0SdNB4IFTdemHqLQ==,iv:cmsTthWak38t9dNXJC+gP35rAk/GiqJSAX9ZVoZG+U8=,tag:rWqqdVrBXX+GGhGF/UhlnQ==,type:str]
    github_app_id: ENC[AES256_GCM,data:cc/3pqPu,iv:MnxV9zqUOdOht+2PtDScgsOXkWqA2y7XJInZyLhtNIY=,tag:Ff/w1HaYQGtp+jODQYKHvQ==,type:int]
    github_app_installation_id: ENC[AES256_GCM,data:q36KLsJeSAQ=,iv:2en9JTw1gsmbNzVfRhUPFg4M/Z0RGEpQ4WbvoqFI48Y=,tag:Y9mMS/Dpl50Ncwz5ifyy+g==,type:int]
    docker_hub_user: ENC[AES256_GCM,data:Pv9euSYZ5T8=,iv:SNhRuHWOK5xqq5TPsb//4dpG4nQ17qsDUkN1Z0gDSiM=,tag://prcWgsZpTMdSXfoM+o0A==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:ORjGQoOEYzDwYcjgGXRzP/WyhtymBuFAL/vyYzWivkp/a9pQ,iv:aGQNexkPESbZ4/PondhGpUmPzMBIsdYCXddVwdCih1I=,tag:4jTrWLpftHWqJT3Zaljikw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apnz8w62yg00n3lux9ys8w59e5pxqqrg28dgzy6ajkr82aeq09gslhhm3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0eGRXNmFnYWRZQWtjT3o3
            ZXVHVTIwWGRSNWJBYTFtekVXNXlvc0hMam5zCmZ1WW00NzlyZWVZdEx2ZEFPNTdu
            eE15SUd0YklJK3VoVjJXRHZhbFZUYjAKLS0tIGMzODlHUzdEdGNyN0NiclFCWlE0
            WXE4cElzek9kVXNWeEtNYkd3Z29jZDAKkY/1VxNniJIX+Inq/1bpYbi+MrIBM4Ga
            YFkj9EhSC0JFbke6tCXFvM4r2E4VS9pnbRC5Qx3b3EWRZRmVu/e1iw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-22T01:44:09Z"
    mac: ENC[AES256_GCM,data:8+9QElRgWw0ecyx4nN/LdxlRMvVia1PAFw7zyr52zN3Np3JGR31lZywe64tRk/GQBY68cDp+vl/wPAMM9I/fbAwWGB4fecj8CRYnA6UsEDUgDkdw4QCCFnbMrYlWg9fUrTAowCTan47gD54eVQkQz4HXoTpomvGsQCeGOJc4eec=,iv:WUU2amSChlX7pPF+NTRDsJs1CmFqVSvY6fZ7hoz+nEU=,tag:RieKEAXId0a9UQjd0wErpw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
