kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    prism_central_endpoint: ENC[AES256_GCM,data:uXOwTOjFrgqZzNuaE8kwkSdlA/YZ,iv:9kuGs8M8Oc+ay6XyUL8h791AocxGADVe3lbqoSqkjfM=,tag:28oIw2J+DMhJuXAmnkYxIQ==,type:str]
    prism_central_user: ENC[AES256_GCM,data:5LuFWuI=,iv:+R+YeocelMqR+nqRSc4ug/5PKW9IaiMhmamyvQjTIpE=,tag:U2Vh/F6UAEeg7iLGXtwgXg==,type:str]
    prism_central_password: ENC[AES256_GCM,data:EphiU/t9Tm3rEuQ=,iv:AuUO3JImAhsCgEmEtpllcocujdU2awH1sEaeTviR5hI=,tag:i7LZlRYUkktvqLzTKBINVg==,type:str]
    prism_element_user: ENC[AES256_GCM,data:N7UfLDg=,iv:LYcm4lXSDtzKJu2Aykr9RQYLYmUuTtNkiOvh5Qj/hUk=,tag:MY62MKZS8Ydi5CnWh0tA+A==,type:str]
    prism_element_password: ENC[AES256_GCM,data:auPe4y6R63eV2mE=,iv:lvzEIuAJ2rQDns4ZkRcI2vHwQuU1jKRV4Y3kw+pZWkk=,tag:kwIlO31cYO9L6CSGWb9DYw==,type:str]
    objects_access_key: ENC[AES256_GCM,data:9FlGRo+5DNAlS718V+XV85YRd1W3wAXTcorDl5y121M=,iv:4DGM8rVvjk6/2xgmiRra+HumlHKI+sJ+47WXHXiphS4=,tag:zXZgk72gg2d/gGCeo9PWqA==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:TjvPRTi3oJizrS7PjIRLRjGFNoGbd/4JjVeg6wZnlyg=,iv:Cg1hluTYF1uS5pINo6cpEfbpzP5CNa/afR5MN6BDYOA=,tag:hywoladi+DPmWph8Jlu5KA==,type:str]
    github_repo_url: ENC[AES256_GCM,data:69O5c/XaCZAfQxPHcTfNx6rY6s2Q9wB5Uv58OX7krUImponJPgnxrCEZOhYq5wsV8/Xa5A==,iv:FRgAXERN/8Y47v9HwNKyl3da0OjsZTPZwjBc8yJbhiM=,tag:W3VyhrHG9ULWOVocEfaEWw==,type:str]
    github_user: ENC[AES256_GCM,data:v8oqmSQCKApMUfwURpY=,iv:J8dQfHGsyY9z8Aupm52taCEPxZW9V6jNZ+8ZNtF6rRE=,tag:eOPaoC+ODX8xKt76PgNK4g==,type:str]
    github_api_token: ENC[AES256_GCM,data:5jSYxUmArdSnuPaISxtYzlU5iO8mRZ17gIZdwFOI71Le5AF8ur2avA==,iv:IBVxCPEehaIqQMs3vHAl7dj87xNNCDG/96hOFWXUU9A=,tag:k0s/cs9g7aNtl8ouNcyLkA==,type:str]
    github_app_id: ENC[AES256_GCM,data:TuuOwlCI,iv:9L4oOnBwVol1t/7X/8lBVggmewoc8yybhcj9v1qBolk=,tag:gJ4hCrrfkIVjLuV+W/kWnA==,type:int]
    github_app_installation_id: ENC[AES256_GCM,data:DHX3EIC4fQo=,iv:zuawhnycqYCqiZ5hJ21gKRIabgeYVXfQVNtb8HmkHbo=,tag:j/+SzzuQl8FY1u/ugbtdEQ==,type:int]
    docker_hub_user: ENC[AES256_GCM,data:XbVu15shKUc=,iv:2SEcfhz2Vkpxez4zLv9FBaEu8/zi2LXz//fPzIQ+N6I=,tag:MbF0I0aRE7Qex8CPDy3x0w==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:8vTFNxov6pStJBAyo95Lf7CGpFEffGL15dimvy3CqxF3yHoE,iv:EyesqrpF6x82uNK3oB14lN70JAnFSknijckOV0zwcLg=,tag:QkHyx39hlPERBy7CxouNMg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apnz8w62yg00n3lux9ys8w59e5pxqqrg28dgzy6ajkr82aeq09gslhhm3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBucjVaUXRub0JXbDhXOEVs
            TjBFZ1VaZlZTV01ZWmNTRlBacGR6Sk1TQlFnCnFJYm9rQlNueXNQbVNGRktabWJv
            RnRPVTJIVzhKb3dmSjZDc0hNbGNidzAKLS0tIFNtQXVsb0xraXpKVy9oMTVMblhs
            bXlUcDMvNzd2VTVuWEgwbktvU2FJdU0Ksk48eCdN7wML+Hwjf6nQHt+OS8iQKGNo
            0ppF0RKt8jxckuRs9mQtiZLugGIAX1I5hO6krOFIDWkh/peUbKgb1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-22T01:42:24Z"
    mac: ENC[AES256_GCM,data:sxGV3sqfpeqMUpnm5cnpG9vHM2Dcn+q5sLa0OzJbCuemg0dpJVIyuFLFZJkx1PJ9cRqNPFkhL3zIMdrgezGuroEh3419oCSFd1L06XdQrbXW49/zZRSkFhUIlQ6M2Lg9SObaCL4mtyf3f9IJ9AK1ZGoP8lt31zzGqNDDjvEOH4Q=,iv:QWSPJPv6fv/Ucj+uNjEqg8Xsiu/UNeuSVZrp/pBi/+o=,tag:wJqMUXoeJtof3WKEJ0Cecg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
