kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    prism_central_endpoint: ENC[AES256_GCM,data:JB3bFZ5IqCK35wlrC3FCSQIzrIm8,iv:XuO5OOFo/SmuHv6d6MBFlCtnS+4sBybW0hoo9tUcWeo=,tag:1dsFKotL9rVtcmMgx9zASg==,type:str]
    prism_central_user: ENC[AES256_GCM,data:8tkAsu0=,iv:7MQTXzu/fakgHL41PlwC9NjWlUX5qBWce9W1sBPnDtA=,tag:PFEe6DeTC+PhXEfvkLgr2A==,type:str]
    prism_central_password: ENC[AES256_GCM,data:E/VndZU9jVprWQo=,iv:h3Y/HBlTmInuUHiBbi9YCmxIfUEZZRayHNbV3lF2tes=,tag:Gswch5lFiXt9PIm0+dKmwg==,type:str]
    prism_element_user: ENC[AES256_GCM,data:TxkoJPs=,iv:FMIDdq+ZcHm9Uu+pERDcNRHsRQ8NAOgv2hIwLp5taG0=,tag:PgPRYV2QPdeuZ/N40zd5uw==,type:str]
    prism_element_password: ENC[AES256_GCM,data:gmNwl6fxB+F7DF0=,iv:NNz0nt2HJZy1ST1rqDG4JLABikhS1M0LJO7MYpwOH34=,tag:RsOoaDpzr/Mkkif/qI+Gsg==,type:str]
    objects_access_key: ENC[AES256_GCM,data:GbP4ol7Hdu6rMgVLbMrFO4SnrHvZvHPFCAfAdTH1gzw=,iv:tyBfyzFcjy/HbregVfaDgeSOT3u7zsTwpsdUQyRybsQ=,tag:dyU7IEUuln83nS/m75bxQg==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:g3POmKNVO5DZMaRLCfkYDJIv2bz+E3icFzhBstSMbME=,iv:xPNFOWO0tFm62fP1ir0I4otTeBC45nqXHXW4vZen+LI=,tag:PsZ+zMfigqPq+4t9NmYJ2g==,type:str]
    github_repo_url: ENC[AES256_GCM,data:ipa+8JR25SOzlq90i2y34D8cjIoWHFtZK3br4jVgfxm9yG8K4wYaFklydgUBxMhMUZAArA==,iv:UlLEyA2kMhQjeAWM0vRh/jyfNjwNRHw7LAY8WFRt4cs=,tag:3KH2SjeaEuGMmPHsIh/X5Q==,type:str]
    github_user: ENC[AES256_GCM,data:z2yHdkY9MbyKYHMhRtc=,iv:hnNuGVrFIF8NRrlTEx7Oo6C3g3bfdfyS8OLWycsUTm8=,tag:SP9Bl60880kWqIrufwKQyw==,type:str]
    github_api_token: ENC[AES256_GCM,data:aqjovGwavxa0mvN+/bE7/gdSPziWw9uGcpboDpDr3G4rJ2josIz/tA==,iv:s8Einty9sBIkoYE/TuNs65haO8UkmRveTL4ygKsDqGc=,tag:Bpz+hmLF75468Pn6zfUO+g==,type:str]
    github_app_id: ENC[AES256_GCM,data:vXTAIkGn,iv:xbBPNbBdivXost+uoAkuTxrB7i2jau70GNK/zP7c8zI=,tag:UkfjCA9fGr99g1S32SiUKw==,type:int]
    github_app_installation_id: ENC[AES256_GCM,data:juIdCfbyLr0=,iv:Xu536fZIomqJvjSDmw59LTT6ryR7LLWnhNud0YfUtMs=,tag:Cz5Kfp0pnBfOvr+ZMjVzaw==,type:int]
    docker_hub_user: ENC[AES256_GCM,data:XACFuidksXA=,iv:6LPaqijX2hrsApUgB9L6PQy8llTWWxay8AYWz8gbISQ=,tag:eu7cU2HpxzdT1Wt9BStKRg==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:a7hIohWDGWgHqXZ73OosAB6jH3siFxq2D9z58qg1XlZkP3JK,iv:K7T/QHfMR/K/K5i3hEwYonkW8tIK5tssLzF7drurt2w=,tag:DBjOWbZGPcuvo3sWUHObTw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apnz8w62yg00n3lux9ys8w59e5pxqqrg28dgzy6ajkr82aeq09gslhhm3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIYThTVmxxSzlabXJ0OTR3
            UlRRYjM1ZG52blBTY2N6WHU3Y0hOUVZGNkdFCjdLV2I3dG5CZS9zb1lhSGxYQW05
            Y0liNGZkUkhhY2YrVzJHRkVyRVBoZUUKLS0tIFBlbFlpTnhwWWhSNFU5OGJrQzBr
            Y1I5S0pjQzlNVTVCTCtkT2FMTWVySHcKlVch/HqWM4bGzaQUztiTu06sBmBUmpCO
            UA21FSLfPH2OPqJ2K2TI/Vm/ysafsxBKlqe6dKTHaPqrfZ39BCjecA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-22T02:52:58Z"
    mac: ENC[AES256_GCM,data:LXPE/1/qqudwJJizAClgYpTgGV1FtjQOs2yXq8y99n/M8BAbMyfL7F/Jcbr34AsiUEGyZ+s8w1ImB0U7ed+64v9NZ/qMzerXyMS7GJUS4jo9/YCE0wUwe4IBlAuaIb6nbzy07i6ZN6NFyM5ayKXoWuSaOYThrvZirDcEoO9Vo+o=,iv:L29TYSOSjik9NBI1hTjPY6whAAEvhSMXdhue0iLIQI4=,tag:LvinKrHIXek4xznXG+cNKA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
