kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    prism_central_endpoint: ENC[AES256_GCM,data:c/6eADVjad/LUSfgWQ32tOxigDF0,iv:oeq2BAsGXXmNJRPI3gv57KyMXHZ92a4/3LVekjx0Sbs=,tag:wIm3QrC5FGZf5pgKCxCg3A==,type:str]
    prism_central_user: ENC[AES256_GCM,data:/jftXIo=,iv:EuJAYS6jky7Glrq+MfQbIkpmvZi+ycyJBdLVHN2Sphs=,tag:0mSaOvucUEX652jMLuFJ0g==,type:str]
    prism_central_password: ENC[AES256_GCM,data:2KhU/VsBsnITCJQ=,iv:YmABa3M0oSZkPukYZ7uGQo9ddA14VQDHeFRBe91Xf24=,tag:TXGaXFM8Z9nHq3h5UyVarg==,type:str]
    prism_element_user: ENC[AES256_GCM,data:+YvLdkc=,iv:7oPywhJz1x6phHBh0xGmwxCF2WuiylbMv/Hk9qM7naQ=,tag:H2QjkpYPKGM1W9RouBch4Q==,type:str]
    prism_element_password: ENC[AES256_GCM,data:Z/5tH8DrQXIo1hI=,iv:JPiFWyC3ywvmiKYAX0pX2bW7RXwTraAmncvQPiWvbfU=,tag:3TFdb8f+e6XmEyHxW9/1AQ==,type:str]
    objects_access_key: ENC[AES256_GCM,data:LOVKpAtcPQsh36q/Cvl6rAUKowLjtPS0A2ip5cVRoK4=,iv:VN8MbP1Q2cdG4KgXA4J2IgZjFBpdXWfWSGpDDSgEUnI=,tag:8EIvZlMsw/Hz3xFVD/eBGA==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:aKQzQ1v6WZ7H/LK/s5A7GunxbuBb2o+jOs+r8URsMxk=,iv:8mzdTpujzJbZPGcgru57eaw5hPpSOs3bjymaGxzPFyM=,tag:WWCTxwJrObZec909yzjhgQ==,type:str]
    github_repo_url: ENC[AES256_GCM,data:II7ljLuhA2LLn30OPxyVRPjyQd6l+QlGOSAVBdx6bMS7U4kuQ0iovrIXlob3Pat71cR9UA==,iv:xAzXD6n4ExnweHQGTLVhd+8e6vT9BEDPnOpoiFLwhSU=,tag:cN5sRJkigVa4w4JuHr4gNQ==,type:str]
    github_user: ENC[AES256_GCM,data:4EdO3lBN9z4cvTqMKqA=,iv:4LRAIWIx9SCJEJ9zdYktWqnMEkCABHHae763p3O3T9o=,tag:NVKFshKtNwJZmm9yyns55A==,type:str]
    github_api_token: ENC[AES256_GCM,data:cyIXIyEKqv6toutGNToT6TEL8UuAOrdC8+AUeKzZM69P+WifvQWulQ==,iv:X9Y0SZR3F9gdMmsMhuowvJYVktrR4YXnvSgx3YR6Ip4=,tag:03RLlITXPGCQzVy6tfz4vg==,type:str]
    github_app_id: ENC[AES256_GCM,data:SauHBA1t,iv:sVopY6pD0JLLnENfrj/41INVHXQi+NZCPobNmdUcfOE=,tag:VIFIOX/gS4Uaqhe7mzmpfw==,type:int]
    github_app_installation_id: ENC[AES256_GCM,data:TvfF8ZvERRw=,iv:Se5quzvFRIoPnZUiehrFfbyxmE4IePvyKDH+mi5rRCM=,tag:zT88uZ/wI7olbXBPyAHxyg==,type:int]
    docker_hub_user: ENC[AES256_GCM,data:7NztnYWYvOQ=,iv:k5FuREXlmshOfVSj7EFDncrPLtx4khpdYhV63rROaZ0=,tag:LAY4x0bqjxrSdsZxSQT1fA==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:N3UUj+HL1aEPPegytGsBKlA8pUscdVUJ8GMbcIVCN3n3zCfs,iv:divVO2c+qbXH+pYJe3hdmHwpVAzslhmfjE9V+mNFLOQ=,tag:flAO+jQJlFCQNTTJpdSbMg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apnz8w62yg00n3lux9ys8w59e5pxqqrg28dgzy6ajkr82aeq09gslhhm3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRRmVEcHo3Qnc2Q20vUzJp
            cVVBN3NRNzB6aUpDRWh2VVc3cmpMMkkxL3c0CjFXcy9iUmhua1liYzVjVTRKMlZU
            LzgrdjZITE45LzJsUDRGNER3NTRCUDAKLS0tIEVRb3NYWkpYZmV5WU1mTGpIMXZp
            OERoY3IwbUd3SjBMUGQwQjN1K1hpVFkKijnaX18Bbvz6ZaS9qmuxl741Cj7SX7Dh
            Md9nbiO58uTYVGAY/T1/ebph2AG8rP3tRQtWb/RIR6Pz8bonUnEIqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-22T02:20:43Z"
    mac: ENC[AES256_GCM,data:/mIl9uW1cZcXeWNa7CK3gmnZbKnBpHHNSlh1Iv8t8bPxdv5AV2kzwYldbUEgF3XuXL8OLtQbwgxnahUS+R+7BPVEK1sWdzo+Fx4fSBmfpRuozIIbPoO+iCZAExVrkPQvEOJSFC6G5uwVud9aB8qCptgPnd5Cgm/c5q8VAzEkqJ4=,iv:cslqYZbJNUQ35wan7ARiHtS8pO+7tqZLo4nxAOGWK9k=,tag:QX98iMDmrH7smabVtJ2zbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
