kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    prism_central_endpoint: ENC[AES256_GCM,data:BrhWIMLBNB7Pe6K1nQb1QEck3SsJ,iv:IbNbnzoqIDw8/Cw95h1OAMVRauhuhUHEnpT8d7STr04=,tag:anF1nb+3YoyhasFCV+K/vQ==,type:str]
    prism_central_user: ENC[AES256_GCM,data:875v2/A=,iv:U+co2AAH9WLvRIah7AFWt8o8qGgvVQAEjiZzZ8Mp4/c=,tag:C82+1J0y68lUctIFzUiiLA==,type:str]
    prism_central_password: ENC[AES256_GCM,data:Muc5aU/OWea/+mE=,iv:CKNAHf0MdFXq46TK7UWPBt+j2dKdbZdaZgG5gg4p1nU=,tag:BY3BM4rQhSZlE1FFmIJiiw==,type:str]
    prism_element_user: ENC[AES256_GCM,data:cAO6lJc=,iv:jXBzr268Lfl5GycJ2gwTa1s2G0+vPzVSfTYpFnzzV/E=,tag:8F/FSMxzuoEdFkHoIBoO1Q==,type:str]
    prism_element_password: ENC[AES256_GCM,data:AFU9dEgX8XxbReE=,iv:aWQ3SNqJFsVTeR/sk2FbGw+4QIAUuEuKYX346rvU4lw=,tag:Oi8NIEN/YUAY1WK7oGJa3g==,type:str]
    objects_access_key: ENC[AES256_GCM,data:Sg7zVWxAvj7Q26j159WuKyksdvi6RBJ+3zcVBUD93q8=,iv:shleM08pxZhmV49jzAbBPOVPSi1htvSDEALtwGsgWOo=,tag:WtEKVlYsLWaPksWE2c++LA==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:6C2phajFhbiadSZj8Rq2/7PeY6oTBbR+FMHGjk70ZWo=,iv:qhhNCxp5a/cRqx1aomm+uYxdE3jWD3MjOb56oH3XAe0=,tag:tRSKKRWLO9YfV4cOHYxfiw==,type:str]
    github_repo_url: ENC[AES256_GCM,data:alqDDfiU2JqKguk8oq1xgfeM+LE5VM0NtDPDGWkOT1WshRN3P8UtwqJyMZ5LToXR4UHiKQ==,iv:4uxcIPzUunTSVM9s7ijoOUuN/NxT/GiX+RsJCsfU128=,tag:UeQESz3ycfRU2mDtvDcjrQ==,type:str]
    github_user: ENC[AES256_GCM,data:sye8Qzl2d+Vd/+xKhTA=,iv:5QGTVbdh0uYeswD35bOJEq8OACzJ7MOeAnkvIpFdKKg=,tag:MLlBXl+8NklygPuVss3bTg==,type:str]
    github_api_token: ENC[AES256_GCM,data:WrYDGSJuksvUfNi5vfwnQgUw0b5C0hl3BWuNpaRYKQsy+RvT9kqecg==,iv:8DuKT08x8k0oBmb7CFFLBIEW2YghgdWKDA9Hjs5Eews=,tag:ztTLiBxjQQv+p1b85TIBTg==,type:str]
    github_app_id: ENC[AES256_GCM,data:Xr2tHuXt,iv:Dvf+VhsDz1MufinBp43KYGkg5pz4Dot25tFz4v2fCHM=,tag:cYfVvkqIkfRGrFbauO7X2Q==,type:int]
    github_app_installation_id: ENC[AES256_GCM,data:kxAWlV2Z62E=,iv:Kcoj3k1hmOJkCRElhtr7c0E/dTQmcOhkjkyeUOLQCDE=,tag:oUgobfe3uT/D1vW92am+QA==,type:int]
    docker_hub_user: ENC[AES256_GCM,data:h/7KcckR8R8=,iv:NnRTQjISy6v5nCD27A3EW7ojwudKLWnwvBNM8XXh39w=,tag:o1ZHt5sX72GKGnfJ5YOaPQ==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:dFhhrkTcb6J9k6023C/ed+xQUurLaohzI+4TWye1T4/DKWAM,iv:gktK2uF0UoMZ/aVsRQutVlSbK5kb98b8s4MddeS6kAw=,tag:RC9Nuk0PLuQ8stf9egtFQA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apnz8w62yg00n3lux9ys8w59e5pxqqrg28dgzy6ajkr82aeq09gslhhm3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqb2JQVWZoV0ptdnZPVDhP
            RklBZXlLOTJUTUx6Vm5OVkYrTXpDVGsycW5JCmZUcWQ0ZkhPRnpveHI0ck9YbVJ2
            Q0duemViSnZwcjdUVW92bVpJL3JuME0KLS0tIGEyeGk4Snh0bWJIV25Makh5d0tH
            dlNoNXEzYmFBUWU0bXNDaW5mVE5rMmMKFipGyt2DfhR9z/YKCkIq/c0kIQ/yPq2/
            vOehiU1yazb8Pe2xIX/KyV8IQPFVj2Xq8DScQv5G8tu2Sv50XuROlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-22T02:36:37Z"
    mac: ENC[AES256_GCM,data:OX4YciVhJ42ebxHQviBFr1FJLFPo3qDrrsyFUi3csioW82HM1XpMQGskFy1lv12Pg+rfLHlTEG0npE4+a99uZJFBnqCPYivlGGW8rjOeu6xM2tPQ6TENwiLatCyfUgbVSKg4punLU3oQDBKIfQq8zbuzDrKbKtAExiKYAsR/ZOk=,iv:76T9m4fKHW3INE83OSSOMnfMhP++s7nhWzUl3Jer2BI=,tag:c/2oXXApUg+1a/1iWrSDRA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
