kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    prism_central_endpoint: ENC[AES256_GCM,data:uTBjeag4Esmt5RzYks4rRGY0MoR5,iv:NmQ+5zIXUP+wiT/z6R3OdnFei1HAngMCA75gVft6arc=,tag:cJCGC0gkdNxQPKFt/ADfmQ==,type:str]
    prism_central_user: ENC[AES256_GCM,data:ekB5mgw=,iv:fKvCVZp6eqdBe+ctvKapKCL6Xf5iQYr7DuASo9y4uEs=,tag:I9SUDV0YAIT46suGsGdNWg==,type:str]
    prism_central_password: ENC[AES256_GCM,data:3Q76+qglCtYyn6A=,iv:brsJSGe/iMRfPmQ5Dw5x3TTApwQ6FWv9IJxlldNyb4U=,tag:4FE0A6i0M03k4ak3BdRvPg==,type:str]
    prism_element_user: ENC[AES256_GCM,data:FnNJxY0=,iv:IUuXtuNDTntMf8i91DrxaVqIQkpkyR1KHACatXqlYCk=,tag:T3y7ANvU3sA4CP4HvZ4O8g==,type:str]
    prism_element_password: ENC[AES256_GCM,data:U8S3R458AiGgMbE=,iv:NOlEO1smRXECP0ZTd2WVoP9q3BUUU+8KWoYLvF7VRvo=,tag:/k20gHQl1LIJ2Tb8Vd1i8Q==,type:str]
    objects_access_key: ENC[AES256_GCM,data:c3IuwTw2yChzrz5jhWs/NMNlQpTtPV5OtlMcQq20fDk=,iv:z5xeGNveJk0DZeCDHqHbMSKEfM/Q3yHQTsSCsAN7GYo=,tag:keNbhRnKyp3rGMoqcmaBpw==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:S/a/PYkaV7fqSwkd1YemNcC6A0qRUVP2a0qXpdxNOhc=,iv:CzkzSM9SgWNKCg40FkQk5i+GjtVc8SedM/WzZy9FqSQ=,tag:qh0bCOAlE8enmdDOW2Tg7A==,type:str]
    github_repo_url: ENC[AES256_GCM,data:K9lLMJ44CCwS4Q3KRKHmMxGEeo4qvDAXQ5KJKlWiD4TG02caWPjlTgkxlQJq0teMkjKo/g==,iv:tKmsXK5iRZSMZ9jNdGbDRiaEPEW9rM2RZHnOdoAMCKA=,tag:rPl8Ewb5rarICGujMjiyrA==,type:str]
    github_user: ENC[AES256_GCM,data:l9g3JEi5J01YTZeT+50=,iv:rHVKTUt4iBZ9QezIdw8y8aSv3uGbgz/VMnZsE5sjkoA=,tag:Plw2ennKc8zs1qAYlEkOOQ==,type:str]
    github_api_token: ENC[AES256_GCM,data:jRJ+m4/3dKzKV1gbPKyBY4U8CjpBHbpVbXSOBKEfywJpAHG4IEHDvA==,iv:05a4D7A6Hamrr0Xas2N2VBfaCK3NqawTXo1TYMwi5P8=,tag:whjpZeqosml0YoHp8d0Y1Q==,type:str]
    github_app_id: ENC[AES256_GCM,data:8AWGOHeu,iv:XyCU42/SuHf5Ek6cso2WZyZDClNX/QZwFIlSOOQD5zA=,tag:q7fB7HEh2Jm3hloYiuI4VQ==,type:int]
    github_app_installation_id: ENC[AES256_GCM,data:NQmA9Gae5B8=,iv:eUluUgJjSHVgbByr/mZeM/6YdDbGgZmzKNo9qauyG0k=,tag:9xjkrQnaTrjgV1JGwoCEcg==,type:int]
    docker_hub_user: ENC[AES256_GCM,data:hkbWoq5DjIY=,iv:ISiq/+fQWrhVCWolZ4cg4owhu9I4NBvD7WQm4D+W/BU=,tag:5aaDSHHZZmbEyxJQpQPuVQ==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:9b/NjYl/99de1DfP+skllMbWLaQIFI+S4DwzVlDp7tHqg7Hl,iv:RpkN7/80YS7nL0sH2pWvXUG58tnaBdX0Jou3ux2OJ/E=,tag:5Ps0FzQw5yRZmfNwNLYYPw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apnz8w62yg00n3lux9ys8w59e5pxqqrg28dgzy6ajkr82aeq09gslhhm3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1VDB6cEl3c205NnBCL1FR
            ZlN1OUNMTVd3amZoN1RtVGxCR1FrblZEejB3CmRaWExHVTcweGF2MTZ0Wm9vSTZ3
            Q0szWFpxWk15OUJOWDdFL0EzNTUyZEEKLS0tIFFwUndtSXNJcWg4SGtQYXhFR2c1
            V2tBRXJSdWJ0UkhBZTdhdUhIMW1SY3cKOcvsBsjywfPz81FbSijZGGaGkmK8BpGy
            t3z5a01T3QGJASe6unVXKPkBmaE+Y2jssrY72sRrHfzQlFXvZZqxMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-22T01:55:00Z"
    mac: ENC[AES256_GCM,data:o8/r5GlQNNxtQX/76rUVlm+ijhdMmikLpzR0pSSKUm19anRxfq+vCuU6J4K23lc7HVQ7ATlJEKl+1kz6RfaobGAZvsIBg2oZrayfKXClWs/cObHqWjEAvMzwcu2GyfZwkYuFdCXpKE/uIkRWx4D5xWB+WKcRDgYQbmCwJ3mOa6M=,iv:BKOzwOe5wgiPc8wvKdiinDtIqgUSB8abn36eAa2KdVE=,tag:7qxNQUVUy5Gfq0cmgsL4XA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
