apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gpu-operator
  namespace: flux-system
spec:
  resources:
  - ../gpu-time-slicing-config.yaml
  components:
  - ../enable-time-slicing
