apiVersion: v1
kind: Namespace
metadata:
  name: velero
  labels:
    toolkit.fluxcd.io/tenant: platform-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: velero
  namespace: flux-system
spec:
  interval: 4h
  url: https://kubernetes.github.io/velero
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: flux-system
spec:
  targetNamespace: ${namespace_name:=velero}
  chart:
    spec:
      chart: velero
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: velero
      version: "*"
  interval: 30m
  values: {}
