apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: grafana
  namespace: flux-system
spec:
  targetNamespace: monitoring
  values:
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      enabled: true
      hosts:
      - grafana.mgmt.*
      ingressClassName: nginx
      tls:
      - hosts:
        - grafana.mgmt.*
        secretName: grafana-tld-secret
