apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
commonLabels:
  nai-llm/profile-name: llm-management
  nai-llm/environment-type: non-prod
components:
  - ../../_profiles/llm-management/non-prod
resources:
  - cluster-secrets.yaml
  - cluster-config.yaml
