kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    prism_central_endpoint: ENC[AES256_GCM,data:Dsl49KOgwlSmVbAAy4dnMgMbWSYFoykz13Z5+n/2hVpr+u4VQPrgoestA/z6RQ==,iv:2d6MLchRMHkDY2+C6V9lgGxIzPT3CncnIbPzkGta9PU=,tag:XYwB2N374BKqM5GiJFDTrw==,type:str]
    prism_central_user: ENC[AES256_GCM,data:BB63nRQ=,iv:4MY4TFzKnfyV5Qxux/qSxLpXp0eiyAzTuf8T+Ogp0wE=,tag:W2y6qVq//hPE+g9Kb6lOrw==,type:str]
    prism_central_password: ENC[AES256_GCM,data:nI3X6z3jDfBYrFM=,iv:uFxrDCoFHrFFzk0vmNMsA+2L2HasHsE0h6qnoVMYdvE=,tag:C+UB3Ro8Q2pTIuKu1fAX7w==,type:str]
    prism_element_user: ENC[AES256_GCM,data:d7hJCVk=,iv:6da992KYoiiFXGB50x2Ioxmt3SnBvBqmgB3GDPrFv54=,tag:p41GxU+3HgYd24Uekq89gQ==,type:str]
    prism_element_password: ENC[AES256_GCM,data:8XTYp/Kik1L2jPY=,iv:gwU5W0wzXMkCuDkGoUDoe8+ce2OgIF7AL6SLqysckWo=,tag:mccvgBa7uzS8N9dcc1VvOA==,type:str]
    github_repo_url: ENC[AES256_GCM,data:d3r9180qIMrQfwTXzaQCeTtcYApa5m+/Q+OxqHFmPWQoUgoMvd+SPSI9b0TmxlcUd8Zfyg==,iv:ieON0DWBuKcy07U+EN+36Hj0A6I+0DEZ+KbrqqQll+0=,tag:2RZl3MdFVB/7yOnNsQX7sg==,type:str]
    github_user: ENC[AES256_GCM,data:g0j4iTSia+iUUKSM7x8=,iv:M4knR+rtGHYww218hJfr54RyJVWibj1rtpl0kP2vQcA=,tag:5+BNug1192ia24uzWIa0BA==,type:str]
    github_api_token: ENC[AES256_GCM,data:i2vKF5xYfRcb+qXi2OhENF++g1UNvwuGfb8omyc0qHrruBh/oeAuBA==,iv:l1jPgGBm5t8/H3f+Obf0taxWoy0HWl7AEsbFIv2tfVc=,tag:cfxWjuWXuOqpBwlp2p4IdQ==,type:str]
    github_app_id: ENC[AES256_GCM,data:74hK34it,iv:CFQcz9kk5Vm8UISIoyHi/77GyrXzkdp8Jj1dGVDOmQY=,tag:yOQSBJZG6LMZJaEdeCahuQ==,type:str]
    github_app_installation_id: ENC[AES256_GCM,data:+ovRIKl6V4g=,iv:Pz8x17QGSvUgh3BqFMAAlZYCQYnrdzEyKO1Kz2lirJk=,tag:1JVJKefFNt/oMpapXdpwdw==,type:str]
    objects_access_key: ENC[AES256_GCM,data:LSI1r2Bx5VmhVvDqqa/3evwyEd8BU449ek/CykANb6s=,iv:mDsRJ25p1bf4obhHWvGNdpY5Dt1wd9jjV82oiq7/t9Y=,tag:Yvctpk32yIQUTb7KMrHxSw==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:8ofvHpJnKAalajoRKWJuaXjpyZSka9InrAAJ925fWww=,iv:KgHyqnTUhzyu4ZN7lLeAxmWfRg8yxZ/AgQVzmT9W27o=,tag:bfD/ey5mvCb16C3KrEk4SQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apnz8w62yg00n3lux9ys8w59e5pxqqrg28dgzy6ajkr82aeq09gslhhm3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxUVpYb2ZVSzZGZ2pWMjFm
            RFFPdDEyNEYzeXc1MTNoQ21YSG0yZ3NGV1RnCkNUcmhlaXY5VGZ6TzV6UEpCNTZn
            MjlsTCtOVlVOVDRoUDBScGxjeTRMVDAKLS0tIENaTDdTUHl6S25FcDZDMDBhNVdw
            RDVRK0ZzcFR1N2tjTmtQOFhmZHNGa00KvB5p/R/zKrNFYyJ9+bbtNO6OKGa391H6
            OPATDL56stDNiBRmAVNfO8wHskfY5yq9bqv2+e5m6GDIPTlZ4zfivA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-07T20:18:34Z"
    mac: ENC[AES256_GCM,data:uzD631uP7AztFsCyyanvEo94itHtUBJXXHsjbj4awoT85o+94c60APzcVfOwDOt2RYQhQ+nYnFK1OR/GgUrolJ7p6tRsS8nKkW/xWkXoC+o2FBuAngTtnwTFp4EeO2BHPq48RA+fKWPaLfzwmJNin9KUwidFbONcc6tkA2exOTs=,iv:wbVhwRLZAB8FMsNMuCT0pVo7aP0FtahtsLHmgiKP6ZU=,tag:93npIyGoSwni/VouHJLn1Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
