kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    prism_central_endpoint: ENC[AES256_GCM,data:1mS4zmlAvFLgz+qKp41jniU2UP5fxxzxtpiN0+RZn7qJE2rDymopXBQ02fdMoA==,iv:QOG8LtxOnYXiA0ZQDC2DfeMfaxFqUPZDVPf7QrjIy1k=,tag:COj6qJjZErrsMHdtZ2/cjQ==,type:str]
    prism_central_user: ENC[AES256_GCM,data:O1ShbwM=,iv:QbU1B77VC9l1uPrMRo5G1/4voFJLNQ7ljfBJQDBH2XI=,tag:9eAi9dRXbII0/XWQScBL+w==,type:str]
    prism_central_password: ENC[AES256_GCM,data:YR4rZdkzW3b0674=,iv:Jxo+hfQ6QsqbP6J2XbVsGARNTVrZzYWGiFzmWmotZYw=,tag:e/5JF5RtfjtGOIomf71/GA==,type:str]
    prism_element_user: ENC[AES256_GCM,data:cLdGBLk=,iv:k3uqAxjbiiFFT4x3jSLKCEJIf2d6dFyu7I08lflmoZM=,tag:ViJXy2gTWAjb7Ry3ahQQHg==,type:str]
    prism_element_password: ENC[AES256_GCM,data:9BOO2Rx8u2QtONs=,iv:EC7OM5sVd0Kqj98tPNxbL3Oy4sQTlnxSrrGH8ItSc2Y=,tag:SfriTCT3I7OzZ7ZOLHcNFw==,type:str]
    github_repo_url: ENC[AES256_GCM,data:sdjLy3U/1jZ8fStL3VBnm9Pdw0niJ9x2m3eBNSUuW1E2GjFWErsgaqHRuXkxZTTM2TqwQg==,iv:wO6W4FDEe0N9BcJiJY+QQfy0ex9UFwbfTkFPO+YrcEE=,tag:6Lko1dkczHCZ+BFZxbz9FA==,type:str]
    github_user: ENC[AES256_GCM,data:E+PgVrvzAMyVjjyBnGk=,iv:cbGTWDBhzTYAOSZERwc+IprscilVNknKLVQgs5POkis=,tag:kZxMxO/sV7DEnIayNrEWZQ==,type:str]
    github_api_token: ENC[AES256_GCM,data:XxDYbBg0Ghz/SJXWae/I31kh0W6+JrZob5q6i8uXUzHAKETwJ01HYQ==,iv:V6M4UJuG6o0a3qBHZztA/RwOMLkL5SSPyBBSlOMd0oY=,tag:S+9C9K9WQ2ZvOwO6SFvkoQ==,type:str]
    github_app_id: ENC[AES256_GCM,data:N5gMeXGJ,iv:7/WzXebTBOmBHxy3NDqN2T0UHSdyD8uOA5RCqc0UiTw=,tag:g7oCXzw+sbmEq3Y3U8f32Q==,type:str]
    github_app_installation_id: ENC[AES256_GCM,data:EcV77qSz0hg=,iv:UiEsL6Syxu9QRxhU5s/gqiaANf1TfRqMR/mQb+3T/g8=,tag:rKua4m3py7RXS2LHIhaTOA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apnz8w62yg00n3lux9ys8w59e5pxqqrg28dgzy6ajkr82aeq09gslhhm3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPY2lJa1NPMkpXTzRkNjJN
            RDIvVy9vS25TTmhhZk1HQ3RGdEpYazJIODNrClEzUytjS1ViWkYyQkVQTEgzZmw0
            bXdhejczTWR3eUQ0VUlxa1JXczV5eEkKLS0tIDdBM2dvVlhsdmhyR0hyRnlybHdT
            b3h5R1JwcUpoUVk4NXdXUFprUm9UMlkKP4vrONrGZ23t5qSKxFb6HWrmUYVw72hP
            zhzK90HiRC1h+uL4mMr+179Zyel8r81aFaWinS5mRjMTCaO3BGSvyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-07T16:50:19Z"
    mac: ENC[AES256_GCM,data:E3jVnHh0qBFvvIRvSUE/rgvgUfVXXZ/R6qHgjksqdCHM6WQVl1pKWwWEVeaVgIEVb+CylZXqUNGbkvSjN7OBZMfQ+Jizf1x+yZALlJmHgSibASBTFdU1tJaPZJSttOHI6Ean3SuzV1oFY9FaTEtTrmBjmQl3sNexwWd7A9CscbU=,iv:YSToCGBKsa3BLjuBbuHK2oQ/8naAfNKQxGgPFkPdC+Q=,tag:UnTxAIBOPZ1t6DwhQPiBHA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
